### PR TITLE
Added ability to use interval.

### PR DESCRIPTION
**Pull request by Mobilpadde**
Was probably forgotten about 😂

### CODE REVIEW

**Comment by molnarmark** [comment]
Thank you :) Resolve the conflicts and i'll merge it.

**Comment by Mobilpadde** [comment]
Sorry, should have checked beforehand :laughing:

**Comment by molnarmark** [comment]
Thanks for your contribution! :tada:

**Comment by Mobilpadde** [comment]
Well, thanks you for making this! :D

**Pull request merged**
